travis:
  secure:
    BINSTAR_TOKEN: J+IoJ79TXPTeTMWF1c7CVXVXlm3b2BPfqlTyaXzoQH7po7E5HlbrfH04ADT3psX96zbofkdXhN0y6s8UAH66sTx9WQGwyV4CjmHPuXmUAP0dSUb9oj8lZ9u+BTnB3G3OYtFLI1T8ppnOHZ4Jq+fP9ic2S3VdzceHuauFAE9A6cxVp2j8Cfq8rBWa4kNUslO/h/mtOeyE+8ouUM5QDw3kbc7JpLwkL6lLXmxngNG6LNaJ24L795Sj/UPwyCIMwbiiRn7EszBsAcpzN9spY/18p/Q4ohL6DE+1X7ySpEReAy+jDtH0YW08Qlaj8NJhlxl+/X9P7Zg06+0pURlRmgWbMxavl5Qlj0Cc9GVWXZ0HWbcdEQdaQpcGOuZjshDbmfZacjw26Q1NNiI5jpdASyEazOxcXQ8FkF8LTez9KSR47qZR0XO3O8hhM+zV3fqSsCVieZNaLsUz845s4N6QVEcw7ZTAz8JU+a6sp97mphHUIpceIMiJ8w1uz1dvcMbQDU3+VFU8NIYrT9/33IpaL8dr5G29/ZHdZKK73VhKzrG5LfRQN+J3muDNWSXa1qIVeEdxUThlK0Gqb4Zhu7jXFrMz9Tpbn81DXDNAgHAH3LbzrEgV41w027Gwa+r1lmx2VHz/t05rjIZCR3bDIf0zIIzf1mSCnCuAk5krBa6DKtVDtmA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
